export const categoryTypes = {
  CREATE_CATEGORY: 'category/CREATE_CATEGORY',
  RENAME_CATEGORY: 'category/RENAME_CATEGORY',
  LOAD_CATEGORIES: 'category/LOAD_CATEGORIES',
  DELETE_CATEGORY: 'category/DELETE_CATEGORY',
}